# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3.0.4
    - name: Install dependencies
      run: |
        conda env create -f environment.yml
        conda install -n transformer flake8
    - name: Lint with flake8
      run: |
        conda run -n transformer flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        conda run -n transformer flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        conda run -n transformer pytest
